%% Within uncertainty example

% Given the output of a LAMMPS annealing simulation, this script computes the
% within-simulation uncertainty and mean value of Tg associated with the
% density-temperature data

%Inputs to this script are:
%(i) a density vs temperature output file generated by the LAMMPS script.  
%(ii) the number of synthetic datasets to generate on the basis of the
%original file

%Given these, the script works as follows.  First, it converts the LAMMPS
%density-temperature data into a format readable by a subsequent analysis
%function, TG_bootstrap.  Then, it inserts this data into the
%aforementioned function, which generates the specified number of
%synthetic datasets and computes the corresponding values of T_g.  The
%average value and sample variance of these T_g values is returned as the
%mean value of Tg and corresponding uncertainty.  The function TG_bootstrap
%automatically plots the data.  More documentation is provided in the
%relevant files

%---------------------------------------------------------
%---------------------------------------------------------
%--------------------- User Inputs -----------------------
%---------------------------------------------------------
%---------------------------------------------------------


%Density file to analyze
filename='rate_5_0.txt';

%How many synthetic sets to generate
numsyntheticsets=120;  

%Options; set to 1 to enable, 0 to disable
testreject=1;           %perform asymptotic convergence test to see if dataset would be rejected
showfigs=1;             %show figures
runinparallel=1;        %generate and analyze synthetic sets in parallel; requires parallel toolbox

%---------------------------------------------------------
%---------------------------------------------------------
%------------------ End User Inputs ----------------------
%---------------------------------------------------------
%---------------------------------------------------------

%Short routine to extract density-temperature data from the LAMMPS file
data=Density_reader_1_01C(filename);

%Density and temperature data
densities=data(:,1);
temperatures=data(:,2);

%"meantg" and "withinvar" are the sample mean and sample variance of the
%synthetic T_g estimates, which are contained in trialcentertgs.  The
%variable "rejected" is 0 if the dataset satisfies the asymptotic
%convergence criterion in TG_bootstrap; otherwise it returns 1.
%(note that if testreject=0, then the function will always return 0 for
%rejected)
[meantg,withinvar,trialcentertgs,rejected]=TG_bootstrap(densities,temperatures,numsyntheticsets,testreject,showfigs,runinparallel);
